# permissions for end users to edit clustermetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "x-metrics.fullname" . }}-clustermetric-editor-role
rules:
- apiGroups:
  - metrics.crossplane.io
  resources:
  - clustermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.crossplane.io
  resources:
  - clustermetrics/status
  verbs:
  - get
