# permissions for end users to view metrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "x-metrics.fullname" . }}-metric-viewer-role
rules:
- apiGroups:
  - metrics.crossplane.io
  resources:
  - metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.crossplane.io
  resources:
  - metrics/status
  verbs:
  - get
