# permissions for end users to view clustermetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermetric-viewer-role
rules:
- apiGroups:
  - metrics.crossplane.io
  resources:
  - clustermetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.crossplane.io
  resources:
  - clustermetrics/status
  verbs:
  - get
